# Generated by Django 5.2.1 on 2025-06-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='exercise_name',
            field=models.CharField(default='헬스', help_text='운동 이름을 입력하세요 (예: 스쿼트, 푸쉬업 등)', max_length=50),
        ),
    ]
