# Generated by Django 5.2.1 on 2025-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_is_analyzed_remove_video_result_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='analysis_videos/'),
        ),
    ]
