# Generated by Django 5.2.1 on 2025-06-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
