# Generated by Django 5.2.1 on 2025-06-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('feedback', models.TextField()),
                ('skeleton_image', models.ImageField(blank=True, null=True, upload_to='skeleton_images/')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='PosePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('keypoints', models.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_points', to='videos.video')),
            ],
        ),
    ]
