# Generated by Django 5.2.1 on 2025-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='problem_joints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
