# Generated by Django 5.2.1 on 2025-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_problem_joints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='skeleton_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_images/'),
        ),
    ]
